[application]

# App (Project) Name
name = "website"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "website"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = [
    "css/all.min.css",
    "css/patternfly.min.css",
    "css/patternfly-addons.css",
    "css/main.css"
]

# Javascript code file
script = [
    "js/all.min.js"
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
